---
services:
  # postgresql database
  postgres:
    image: postgres:15
    restart: "no"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432

  # kratos migration
  kratos-migrate:
    image: oryd/kratos:v1.1.0
    restart: "no"
    environment:
      - DSN=postgres://fims-db:NFLApODULateMyoKERvaGalaQUeYeBRIdwOndiVeRseYeTeSoM@postgres:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4&TimeZone=UTC
    volumes:
      - type: bind
        source: ./ory-kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  # kratos, our IdP
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.1.0
    restart: "unless-stopped"
    environment:
      - DSN=postgres://fims-db:NFLApODULateMyoKERvaGalaQUeYeBRIdwOndiVeRseYeTeSoM@postgres:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4&TimeZone=UTC
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./ory-kratos
        target: /etc/config/kratos
    ports:
      - 4434:4434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  # oathkeeper, our gateway
  oathkeeper:
    image: oryd/oathkeeper:v0.40.7
    restart: "no"
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - type: bind
        source: ./ory-oathkeeper
        target: /etc/config/oathkeeper
    ports:
      - 4455:4455
    extra_hosts:
        - "host.docker.internal:host-gateway"
    networks:
      - default
      
networks:
  default:
    driver: bridge
    enable_ipv6: true