version: "3"

services:
  # postgresql database
  postgres:
    # profiles:
    #   - "db"
    image: postgres:13
    restart: "no"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432

  # database admin
  adminer:
    # profiles:
    #   - "db"
    image: adminer:latest
    restart: "no"
    ports:
      - 8080:8080

  # kratos migration
  kratos-migrate:
    # profiles:
    #   - "kratos"
    image: oryd/kratos:v0.11.0
    restart: "no"
    environment:
      - DSN=postgres://93fe5029-1886-4b63-94ca-35c503a52eff:hePrAqafu&5Ep49V8th9@postgres:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4&TimeZone=UTC
    volumes:
      - type: bind
        source: ./ory-kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  # kratos, our IdP
  kratos:
    # profiles:
    #   - "kratos"
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.11.0
    restart: "unless-stopped"
    environment:
      - DSN=postgres://93fe5029-1886-4b63-94ca-35c503a52eff:hePrAqafu&5Ep49V8th9@postgres:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4&TimeZone=UTC
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./ory-kratos
        target: /etc/config/kratos
    ports:
      - 4434:4434
  
  mailslurper:
    # profiles:
    #   - "kratos"
    image: oryd/mailslurper:latest-smtps
    restart: "no"
    ports:
      - 4436:4436
      - 4437:4437

  # oathkeeper, our gateway
  oathkeeper:
    # profiles:
    #   - "oathkeeper"
    image: oryd/oathkeeper:v0.40.0
    restart: "no"
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - type: bind
        source: ./ory-oathkeeper
        target: /etc/config/oathkeeper
    ports:
      - 4455:4455
